export const products = [
    {
        id: 1,
        img: "https://www.w3schools.com/images/lamp.jpg",
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 8295,
        gender: "men",
    },
    {
        id: 2,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 3,
        price: 10295,
        gender: "men",
    },
    {
        id: 3,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 2,
        price: 9695,
        gender: "women",
    },
    {
        id: 4,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 5,
        price: 8295,
        gender: "women",
    },
    {
        id: 5,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 5,
        price: 10295,
        gender: "men",
    },
    {
        id: 6,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "men",
    },
    {
        id: 7,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 1,
        price: 8295,
        gender: "women",
    },
    {
        id: 8,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Vans",
        details: "Nike Dunk High Retro SE",
        rating: 2,
        price: 10295,
        gender: "kids",
    },
    {
        id: 9,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg}",
        title: "Vans",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "kids",
    },
    {
        id: 10,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Puma",
        details: "Nike Dunk High Retro SE",
        rating: 4,
        price: 10295,
        gender: "men",
    },
    {
        id: 11,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Puma",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 9695,
        gender: "men",
    },
    {
        id: 12,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Adidas",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 5,
        price: 8295,
        gender: "women",
    },
    {
        id: 13,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Adidas",
        details: "Nike Dunk High Retro SE",
        rating: 2,
        price: 10295,
        gender: "kids",
    },
    {
        id: 14,
        img: "https://photo2.tinhte.vn/data/attachment-files/2021/05/5471652_cover_sosanh_macbook_surface.jpg",
        title: "Adidas",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "kids",
    },
];
